sudo: false
language: rust
rust:
- nightly
- beta
- stable
- 1.11.0
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo --only stable doc -- --no-deps
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: UlhmvtjXA2qJcxZ8+LbxumDcxr8gd3Ldy5L/WjBZ2WW8xvehqDWbB3a3+ewAXBTn9I6hJZJ+nnLLySyxf2kRnhVjIAGoe6mVLWpacke4brQwA4630nTHTTyukDtlEds65OiZJhGa1ubnmzj1K0/j1hqtYefxii5WEA3xf85NkrLNFQoOiP/9SAnJbmxjOzwPhU9awsTylcwg3+VB2tu2gCKBUrTCtMQQFKOl7hTxr2BgkOYDN9WsvMAZ3cDipusb/HK6lCe/+15nl5wqNTpBStA3g2TzlKcp8k6eEt0G6kC2zfdlUoO+HUqWZ8y+YtYNkMXYhm6odSxRThOkFeiBETjurXHhcfmIBWtj2+eKbQOuoAgXAqiW9pM9VWvpaHkNMmc+QcWCnznTe1+8jgI3IeuolM5ND4QLXskPB4R8SORSFMzatw9At+yXnsWXLX/E0HfpQfNnPFqp9nU8XJUV99foakW28Xe+lDjFSH2OHMbmjNq0tefhuFzYPc0jGPNh9j8D1PiS3CLsETVbu0SK9A/JaLbbdQwwzOsaM86J/gC8k+TZ8u0WvoII/nDskVLVshvtJPj22L9Uaf4EvOzlVzDiBwbPqFpVThBL2/RE4L+dIIcXsO2ahDFYz4jk15+WY1TQvQqU39hza+ZNcv3U+y7ErVvCM5aSd7hDVZUWlMc=
