sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
  - 1.20.0
script:
  - cargo test --no-default-features
  - cargo test --no-default-features --features caf
  - cargo test --no-default-features --features mp4
  - cargo test --all-features
  - cargo test --release --all-features
before_deploy:
  - cargo doc --all-features --no-deps
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "OxQ8OAt6ocVO0TNjJoI9/wZfsrWT5GAEtDthTmDyGCgeauT4szemL1pXVZZqR/Y6fibiN5OQgQ/cSuaf28Zio1LgWwpGRYnbwKhDVjzNAFQJ7eFm4spvIvSGAj7LRkS+J0qXgh/AixTDNbEr8JF/zhbibGpxiZmvEdFIC62sSU4V7Ue4TWpoZh8ja/YEH1zJXICemvNN21jknFF6vPT/sdrzUTTjFw9r0Lzb9+AnaoJ/N6y017gzsPx6OxpxDzMM5wOsJFg6dU+MXGN+vGvVeP6+3N8rbmVlTKy3f2FV+sX3k6yFOKCUkmGSbv8d41qgu3QOjebMAjKWTVbJO2aF3W34Q/Fx8TzYoqXEHlCloub0c8Nq658GdUAezUJQjLfscxbFUtftZVdROZAGF/TjliHseN7jMvF9KiGBNwEevZLnOBXgxL6xzI/R2Iwlwmy/6ZmM1GtUh/kj5nT8laAaD2/B51MozJ3jF1cByUDUkvPTyYMDAxsU9/2t2RmTlJi/RvdkhKd/kWzRK2u3jbSZtIGyzkiv2XGX4br20agRwc4v6yyyIeEAPrZkV1mlYGWDc6A/JCT1s09ngscSSWrq+J4BvoMbJmKBny7Nu+NRV9uvE2KoYlT977ewY6dE4H+ISa3HpSL9cC6rJxaY61j3fNBTUTa9OElAjgA7ZPuEGBU="
  local_dir: target/doc/
  on:
    branch: master
    os: linux
    rust: nightly
